# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04431a3b8a5931d38e02cff6c66f549a2937c8be41b51c01eddcfe167c072f5a268c3795a3134f5972823dcce44e59fa53a301e0e44adfd3e3d28041855d688a

test:
  secret_key_base: 1346e1067e4ae78bc846a3d0c2fbd096055586906035a063ff1eb72c35554084e083dec40ee5c195d3aad4668ab401074ee281547f16dc5d550684a2074a9645

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
